### PR TITLE
Fixes for outstanding issues.

### LINKED ISSUE #7: License File
Can you add license file that describe what license this project is

### PR DESCRIPTION
**Pull request by troglobit**
Signed-off-by: Joachim Nilsson <troglobit@gmail.com>

### CODE REVIEW

**Review by elfring — COMMENTED** [review]
How do you think about to take care also for [remaining unchecked return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values")?

**Comment by troglobit** [comment]
Sure, do you have a list of any particular syscalls/APIs in mind, or a Coverity Scan run perhaps, that I can have a look at?

**Comment by elfring** [comment]
>…, do you have a list of any particular syscalls/APIs in mind, …

- How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for this software?
- Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++")?
  
  How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by troglobit** [comment]
I can help set up Coverity Scan, I've done that for quite a few projects of my own. It's been very useful in finding impossible bugs.

The other parts I have no experience with, but seem like interesting topics to put in the issue tracker with a *help wanted* tag, or similar so other people can pitch in.

**Comment by elfring** [comment]
* Does the tool “Coverity Scan” check usage of POSIX functions?
* How do think about to try additional free (and not only gratis) software tools out?

**Comment by troglobit** [comment]
Not really sure what you mean, Coverity Scan is like cppcheck, lint, or sparse, but on massive amounts of steroids.  It mocks behaviour of certain functions know to behave bad just to see how your own code would react, and also finds logical errors 40 levels down that no human brain could possibly dream up.

There are lots of other tools as well that can be run, valgrind immediately comes to mind. The project should explore all the free ones that conveniently have a GitHub API and/or can be run via Travis-CI. But that's just IMHO. You're the maintainer and should set out goals for your own project. I've just committed to fixing a few bugs.

**Comment by elfring** [comment]
>You're the maintainer …

Not for the software “pingfs” so far. - But I am trying to point further improvement possibilities out.


>I've just committed to fixing a few bugs.

Thanks for your contributions.

Would you become interested to adjust any more source code places?

**Comment by troglobit** [comment]
@elfring Ah, now I see, sorry my mistake.

pingfs is a cool/funny idea, just wanted to pitch in with some quick fixes. I have a lot of other commitments as well, but we'll see, maybe :)

**Pull request merged**
